modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Nobodiiiii/Create-Biotech/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Nobodiiiii/Create-Biotech"
logoFile = "logo.png"
authors = "${mod_authors}"
description = '''${mod_description}'''
enumExtensions = "META-INF/enumextensions.json"

[[mixins]]
config = "create_biotech.mixins.json"

[[mixins]]
config = "create_biotech_sable.mixins.json"

[[mixins]]
config = "create_biotech_alternate_current.mixins.json"

[[mixins]]
config = "create_biotech_lionfish.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "${create_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "sable"
type = "optional"
versionRange = "${sable_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jei"
type = "optional"
versionRange = "${jei_version_range}"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "jade"
type = "optional"
versionRange = "[15.10,)"
ordering = "AFTER"
side = "CLIENT"

